### ISSUE TITLE
Apanova – Duplicate name

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers_Dan_Marius#1]
ENVIROMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1. Open URL in browser
2. Type the name of the company in the search bar
3. Check name of the company

EXPECTED RESULT:
The company name must appear only once.

ACTUAL RESULT:
The company name appears duplicated.

![Screenshot_5](https://github.com/peviitor-ro/Scrapers_Dan_Marius/assets/137804590/561a0012-2e5b-470e-9fdf-1d4b6da0f394)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by RafayBeatrice** [comment]
It work!
