### ISSUE TITLE
Promek - The career link is not good

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers_Dan_Marius#10]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Write the job title
See the job list.

EXPECTED RESULT:
To see the available jobs.

ACTUAL RESULT:
You see 0 jobs available.
This is a good link for careers https://www.careers-page.com/promelek-xxi
![Screenshot_2](https://github.com/peviitor-ro/Scrapers_Dan_Marius/assets/137804590/c5d61357-e9d9-4217-91bd-6c842364d513)
![Screenshot_3](https://github.com/peviitor-ro/Scrapers_Dan_Marius/assets/137804590/6c7095f8-e0ef-45a1-b5bc-2681b43ef2c3)

**Comment by dan-marius** [comment]
Company moved Jobs to new link. Old Lik not actual anymore https://promelek.ro/cariere:
![image](https://github.com/peviitor-ro/Scrapers_Dan_Marius/assets/21097752/de569741-021a-4e81-a7eb-4a1f7644c032)
New Scraper has to be programed for the jobs link:
https://www.careers-page.com/promelek-xxi

**Comment by dan-marius** [comment]
Rebuild the scraper entirely. Should work now.

**Comment by dan-marius** [comment]
Please check again.
