### ISSUE TITLE
Altex - Jobs do not start with a capital letter

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers_Dan_Marius#11]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Write the job title
See the job list.

EXPECTED RESULT:
To see all jobs with capital letters.

ACTUAL RESULT:
You see all jobs with lowercase letters.
![Screenshot_2](https://github.com/peviitor-ro/Scrapers_Dan_Marius/assets/137804590/45b373af-4fcd-4c4c-914e-b826f32941aa)
![Screenshot_3](https://github.com/peviitor-ro/Scrapers_Dan_Marius/assets/137804590/78465387-1719-4441-adb7-7d537a6f6e65)

**Comment by dan-marius** [comment]
Fixed, please try again.
