### ISSUE TITLE
CNI - Data of the jobs are expired

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers_Dan_Marius#2]
ENVIROMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1. Open URL in the browser
2. Go to CNI company
3. Check CNI company website
4. Check the validity of the jobs

EXPECTED RESULT:
The jobs have a valid date.

ACTUAL RESULT:
The jobs have data expired in 2020 and 2022.

![Screenshot_2](https://github.com/peviitor-ro/Scrapers_Dan_Marius/assets/137804590/4717aae5-0a8a-41c8-b3c9-e9d52e1e0406)

![Screenshot_17](https://github.com/peviitor-ro/Scrapers_Dan_Marius/assets/137804590/ec43b85a-5e6d-4c34-852b-ece2c4fb4853)

**Comment by dan-marius** [comment]
Nu raspundem de calitatea datelor scrapuite, datele sunt ale companiei scrapuite.
