### ISSUE TITLE
Hamilton - The number of jobs is different

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers_Dan_Marius#3]
ENVIROMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Type the name of the company in the search bar
Check the jobs

EXPECTED RESULT:
To see all the jobs.

ACTUAL RESULT:
On the job page are 15 jobs posted and our page is 13 page. Are missing "Assembly Assistant" and "Assembly Operator".

![Screenshot_6](https://github.com/peviitor-ro/Scrapers_Dan_Marius/assets/137804590/801792cc-72c7-4089-be21-bcba22b108d4)

**Comment by dan-marius** [comment]
I have modified the API_Key to push the results into production database.
Please check again and closeissu if fixed. Else, please give me feedback.

Thank you!

**Comment by RafayBeatrice** [comment]
It work!
