### ISSUE TITLE
Hamilton- The number of jobs are different

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers_Dan_Marius#4]
ENVIROMENT: production
URL: https://firme.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Type the name of the company in the search bar
Check the jobs

EXPECTED RESULT:
To see all the jobs.

ACTUAL RESULT:
On the job page are 16 jobs posted and our page is 15 page. Are missing "Team Leader Process Care (temporary)".

![Screenshot_4](https://github.com/peviitor-ro/Scrapers_Dan_Marius/assets/137804590/64e19e85-e0f4-4ec9-84a0-b821ba10e772)

**Comment by dan-marius** [comment]
Scrapers are run once/day automatically. If a job is posted before the scraper is run, the job numbers must be from the day before. Anyway, now I have run the scraper manually and should be fine. If not please let me know.
