### ISSUE TITLE
Hamilton - Status "Inactive"

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers_Dan_Marius#5]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Type the name of the company in the search bar
Run scraper
Check the status
EXPECTED RESULT:
Status to be "Active"

ACTUAL RESULT:
Status is "Inactive"

![Screenshot_3](https://github.com/peviitor-ro/Scrapers-UI/assets/137804590/299b9375-d6ed-480a-a6bf-4a0e23f86c63)

**Comment by lalalaurentiu** [comment]
@dan-marius  scraper-ui works perfectly but it seems the scraper is not working properly
![Image](https://github.com/peviitor-ro/Scrapers-UI/assets/67306273/527fe172-5c3d-4c1e-a03c-232161fc5da7)

**Comment by lalalaurentiu** [comment]
@dan-marius  scraper-ui works perfectly but it seems the scraper is not working properly
<img width="1440" alt="Screenshot 2023-12-14 at 22 58 53" src="https://github.com/peviitor-ro/Scrapers_Dan_Marius/assets/67306273/903e8f87-26f0-4e5a-aa9b-4e5193efc6a1">

**Comment by dan-marius** [comment]
Cannot reproduce. Runs fine in Actions on Github: Python 3.10.13
<img width="1233" alt="Screenshot 2023-12-15 at 09 31 18" src="https://github.com/peviitor-ro/Scrapers_Dan_Marius/assets/21097752/614f9fd2-35ee-434a-9505-ea0dd2fb1184">

And locally with Python 3.11.4
<img width="985" alt="Screenshot 2023-12-15 at 09 30 01" src="https://github.com/peviitor-ro/Scrapers_Dan_Marius/assets/21097752/881e850f-0e33-457b-882f-f630a8e3d1b6">

Will investigate further.

**Comment by dan-marius** [comment]
@lalalaurentiu Can you check if pypeteer works fine on your machine?
<img width="600" alt="Screenshot 2023-12-15 at 09 57 54" src="https://github.com/peviitor-ro/Scrapers_Dan_Marius/assets/21097752/0b802b31-7b8f-406a-adae-ac04d4470f93">

**Comment by dan-marius** [comment]
[Scrapers UI] is deprecated. Closed.
