### ISSUE TITLE
Maviprod - Oradea, Arad, Salonta is not a city in Romania

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers_Dan_Marius#7]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/maviprod/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Run Scraper
Check the jobs

EXPECTED RESULT:
To see the available towns.

ACTUAL RESULT:
You see Oradea, Arad, Salonta is not a city in Romania.
![Screenshot_1](https://github.com/peviitor-ro/Scrapers_Dan_Marius/assets/137804590/7b55792f-6794-476e-96a3-d0e70dad39d6)

**Comment by dan-marius** [comment]
Fixed. Please re-run tests.
