### ISSUE TITLE
Bengen - Status "Inactive"

### ISSUE THREAD

**Issue by RafayBeatrice** [peviitor-ro/Scrapers_Dan_Marius#8]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Type the name of the company in the search bar
Run scraper
Check the status
EXPECTED RESULT:
Status to be "Active"

ACTUAL RESULT:
The status is "Inactive"

![Screenshot_15](https://github.com/peviitor-ro/Scrapers-UI/assets/137804590/9e0d60b7-3bf7-41c2-9840-e3afe7d4de4a)

**Comment by lalalaurentiu** [comment]
Nu mai puneti ce returneaza metoda ca scrapers ui nu suporta decat python 3.8 maxim
![Screenshot 2024-01-29 at 14 00 17](https://github.com/peviitor-ro/Scrapers_Dan_Marius/assets/67306273/db77c8ae-ec4b-4d00-b559-97fd76fae2a8)

**Comment by dan-marius** [comment]
Got it, Laurentiu. Modificat, Te rog retesteaza Bea.

**Comment by RafayBeatrice** [comment]
Verificat.
